name = "potion_problem"
version = "0.1.0"
keywords = ["math", "probability", "formal-verification"]
defaultTargets = ["PotionProblem"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "PotionProblem"